[phases.setup]
nixPkgs = [
  "python310", 
  "gcc", 
  "libjpeg", 
  "zlib", 
  "libpng", 
  "libx11", 
  "libglvnd", 
  "git", 
  "alsa-lib", 
  "libpulseaudio"
]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.start]
cmd = "python agent.py"
